version: '3'
services:
  mongo_db:
    container_name: database_container
    image: mongo:latest
    restart: always
    volumes:
      - mongo_db:/data/db
  
  app:
    build: .
    ports:
      - 8000:8000
    environment:
      - APP_NAME=musicplayer
      - PORT:8000
      - DB_URL:mongodb+srv://bereketdinku:beki1234@cluster0.a7un02o.mongodb.net/musictest
    depends_on:
      - mongo_db
volumes:
  mongo_db: {}